language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - cd api
  - pytest --cov=api
  - coverage report -m
after_success: 
- coveralls