language: python

python:
    - "3.6"

# install dependency
install: 
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov


script:
  - pytest -v --cov api --cov-report term-missing

after_success: 
- coveralls